# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02e59ff8e51d8ff37c99ff73c3e80d896003d803bfe901a45572b653610e694a6c643dd67791a6f9779080c8debb3c9c835327c04bc2f45786bb3bc5bf96878d

test:
  secret_key_base: e1bdfa0605c081639e5c7dd3c8c0845ef6dbdf8005648b225bbf98940b9edf2dc495f3d37eced5745529bed9053d202c7871f88b734fc2f5f756ac8540b8fe54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
